/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "mysql adapter settings": {                       "en": "Adapter settings for mysql",                       "de": "Adaptereinstellungen für mysql",                   "ru": "Настройки адаптера для mysql",                     "pt": "Configurações do adaptador para mysql",            "nl": "Adapterinstellingen voor mysql",                   "fr": "Paramètres d'adaptateur pour mysql",               "it": "Impostazioni dell'adattatore per mysql",           "es": "Ajustes del adaptador para mysql",                 "pl": "Ustawienia adaptera dla mysql",                    "uk": "Налаштування адаптера для mysql",                  "zh-cn": "mysql的适配器设置"},
};